### ISSUE TITLE
New-CmsSpaceAccessMethod not adding URI

### ISSUE THREAD

**Issue by pberenyi** [tomlarse/PsAcano#35]
Hi,

I was trying to add some access methods on a CMS to a space by using the New-CmsSpaceAccessMethod cmdlet, but although I have specified the Uri parameter (-Uri xyz.cms) the access method is created without an URI (and is not working properly). Using the API directly with Postman and specifying the same URI as raw data, the access method to the space is created with the URI. Can you please check this?

Thanks

**Comment by tomlarse** [comment]
Hi

Thanks for catching this, there was a bug in both set- and new- for the accessmethod functions. I will upload a fix!
